# Generated by Django 5.0.6 on 2024-08-11 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='developer_id',
            new_name='developer',
        ),
    ]
