# Generated by Django 5.0.6 on 2024-08-11 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='username',
            new_name='name',
        ),
    ]
