# Generated by Django 5.0.6 on 2024-08-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_rename_username_developer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='\\images'),
        ),
    ]
