# Generated by Django 5.0.6 on 2024-08-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_developer_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
